name: Villages
version: ${version}
main: org.clockworx.villages.VillagesPlugin
description: Paper Enhanced Villages - Boundary calculation, region protection, welcome signs
api-version: '1.21.11'
bootstrapper: org.clockworx.villages.VillagesPluginBootstrap

# Soft dependencies - these plugins are optional but enhanced if present
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: false
    RegionGuard:
      load: BEFORE
      required: false
    BlueMap:
      load: AFTER
      required: false